import type { Course, Paper, Teacher } from "./types";

export const mockTeachers: Teacher[] = [];

/** Full BSCS 2023-27 scheme — 46 courses */
export const mockCourses: Course[] = [
  { id: 1, name: "Programming Fundamentals", code: "CS-101", slug: "programming-fundamentals", semester: 1, department: "Computer Science" },
  { id: 2, name: "Digital Logic Design", code: "CS-102", slug: "digital-logic-design", semester: 1, department: "Computer Science" },
  { id: 3, name: "Application of ICT", code: "GEDU-104", slug: "application-of-ict", semester: 1, department: "Computer Science" },
  { id: 4, name: "Functional English", code: "GEDU-101", slug: "functional-english", semester: 1, department: "Computer Science" },
  { id: 5, name: "Islamic Studies", code: "GEDU-102", slug: "islamic-studies", semester: 1, department: "Computer Science" },
  { id: 6, name: "Object Oriented Programming", code: "CS-151", slug: "object-oriented-programming", semester: 2, department: "Computer Science" },
  { id: 7, name: "Computer Organization & Assembly Language", code: "CS-152", slug: "computer-organization-assembly", semester: 2, department: "Computer Science" },
  { id: 8, name: "Computer Networks", code: "CS-153", slug: "computer-networks", semester: 2, department: "Computer Science" },
  { id: 9, name: "Expository Writing", code: "GEDU-151", slug: "expository-writing", semester: 2, department: "Computer Science" },
  { id: 10, name: "Discrete Structures", code: "GEDU-154", slug: "discrete-structures", semester: 2, department: "Computer Science" },
  { id: 11, name: "Ideology and Constitution of Pakistan", code: "GEDU-152", slug: "ideology-constitution-pakistan", semester: 2, department: "Computer Science" },
  { id: 12, name: "Data Structures", code: "CS-201", slug: "data-structures", semester: 3, department: "Computer Science" },
  { id: 13, name: "Artificial Intelligence", code: "CS-202", slug: "artificial-intelligence", semester: 3, department: "Computer Science" },
  { id: 14, name: "Software Engineering", code: "CS-203", slug: "software-engineering", semester: 3, department: "Computer Science" },
  { id: 15, name: "Applied Physics", code: "GEDU-205", slug: "applied-physics", semester: 3, department: "Computer Science" },
  { id: 16, name: "Calculus and Analytic Geometry", code: "GEDU-202", slug: "calculus", semester: 3, department: "Computer Science" },
  { id: 17, name: "Introduction to Management", code: "GEDU-237", slug: "intro-to-management", semester: 3, department: "Computer Science" },
  { id: 18, name: "Analysis of Algorithms", code: "CS-251", slug: "analysis-of-algorithms", semester: 4, department: "Computer Science" },
  { id: 19, name: "Database Systems", code: "CS-252", slug: "database-systems", semester: 4, department: "Computer Science" },
  { id: 20, name: "Operating Systems", code: "CS-253", slug: "operating-systems", semester: 4, department: "Computer Science" },
  { id: 21, name: "Entrepreneurship", code: "GEDU-251", slug: "entrepreneurship", semester: 4, department: "Computer Science" },
  { id: 22, name: "Professional Practices", code: "GEDU-267", slug: "professional-practices", semester: 4, department: "Computer Science" },
  { id: 23, name: "Civics and Community Engagement", code: "GEDU-252", slug: "civics-community-engagement", semester: 4, department: "Computer Science" },
  { id: 24, name: "Pakistan Studies", code: "HU-112", slug: "pakistan-studies", semester: 4, department: "Computer Science" },
  { id: 25, name: "Computer Architecture", code: "CS-301", slug: "computer-architecture", semester: 5, department: "Computer Science" },
  { id: 26, name: "Advance Database Management Systems", code: "CS-302", slug: "advance-database-systems", semester: 5, department: "Computer Science" },
  { id: 27, name: "Computer Graphics", code: "CS-321", slug: "computer-graphics", semester: 5, department: "Computer Science" },
  { id: 28, name: "Information Security", code: "CS-353", slug: "information-security", semester: 5, department: "Computer Science" },
  { id: 29, name: "Multivariable Calculus", code: "MATH-384", slug: "multivariable-calculus", semester: 5, department: "Computer Science" },
  { id: 30, name: "Technical & Business Writing", code: "ENG-384", slug: "technical-business-writing", semester: 5, department: "Computer Science" },
  { id: 31, name: "Theory of Automata", code: "CS-351", slug: "theory-of-automata", semester: 6, department: "Computer Science" },
  { id: 32, name: "Object Oriented Analysis and Design", code: "CS-303", slug: "ooad", semester: 6, department: "Computer Science" },
  { id: 33, name: "Digital Image Processing", code: "CS-452", slug: "digital-image-processing", semester: 6, department: "Computer Science" },
  { id: 34, name: "Web Technologies", code: "CS-355", slug: "web-technologies", semester: 6, department: "Computer Science" },
  { id: 35, name: "Probability & Statistics", code: "STAT-379", slug: "probability-statistics", semester: 6, department: "Computer Science" },
  { id: 36, name: "Human Computer Interaction", code: "CS-404", slug: "human-computer-interaction", semester: 6, department: "Computer Science" },
  { id: 37, name: "Compiler Construction", code: "CS-401", slug: "compiler-construction", semester: 7, department: "Computer Science" },
  { id: 38, name: "Parallel and Distributed Computing", code: "CS-451", slug: "parallel-distributed-computing", semester: 7, department: "Computer Science" },
  { id: 39, name: "Mobile Application Development", code: "CS-354", slug: "mobile-application-development", semester: 7, department: "Computer Science" },
  { id: 40, name: "Linear Algebra", code: "MATH-378", slug: "linear-algebra", semester: 7, department: "Computer Science" },
  { id: 41, name: "Internship", code: "CS-497", slug: "internship", semester: 7, department: "Computer Science" },
  { id: 42, name: "Final Project (Part I)", code: "CS-498", slug: "final-project-part-1", semester: 7, department: "Computer Science" },
  { id: 43, name: "Software Testing & Quality Assurance", code: "CS-402", slug: "software-testing-qa", semester: 8, department: "Computer Science" },
  { id: 44, name: "Visual Programming", code: "CS-352", slug: "visual-programming", semester: 8, department: "Computer Science" },
  { id: 45, name: "Introduction to Marketing", code: "MKT-373", slug: "introduction-to-marketing", semester: 8, department: "Computer Science" },
  { id: 46, name: "Final Project (Part II)", code: "CS-499", slug: "final-project-part-2", semester: 8, department: "Computer Science" },
];

/** Existing sample papers mapped to correct course ids above */
export const mockPapers: Paper[] = [
  { id: 1, courseId: 17, title: "Introduction to Management Mid 2024", year: 2024, examType: "mid", teacherId: null, teacher: null, fileUrl: "/papers/by-course/intro-to-management-mid-2024.pdf", status: "approved" },
  { id: 2, courseId: 17, title: "Introduction to Management Final 2024", year: 2024, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/intro-to-management-final-2024.pdf", status: "approved" },
  { id: 3, courseId: 15, title: "Applied Physics Mid 2024", year: 2024, examType: "mid", teacherId: null, teacher: null, fileUrl: "/papers/by-course/applied-physics-mid-2024.pdf", status: "approved" },
  { id: 4, courseId: 15, title: "Applied Physics Final 2024", year: 2024, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/applied-physics-final-2024.pdf", status: "approved" },
  { id: 5, courseId: 12, title: "Data Structures Final Fall 2024", year: 2024, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/data-structures-final-2024.pdf", status: "approved" },
  { id: 6, courseId: 16, title: "Calculus and Analytic Geometry Final 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/calculus-final-2025.pdf", status: "approved" },
  { id: 7, courseId: 13, title: "Artificial Intelligence Final Fall 2024", year: 2024, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/artificial-intelligence-final-2024.pdf", status: "approved" },
  { id: 8, courseId: 23, title: "Civics & Community Engagement Paper", year: 2025, examType: "other", teacherId: null, teacher: null, fileUrl: "/papers/by-course/civics-paper.pdf", status: "approved" },
  { id: 9, courseId: 23, title: "Civics & Community Engagement Mid 2025", year: 2025, examType: "mid", teacherId: null, teacher: null, fileUrl: "/papers/by-course/civics-mid-2025.pdf", status: "approved" },
  { id: 10, courseId: 19, title: "Database Systems Mid 2025", year: 2025, examType: "mid", teacherId: null, teacher: null, fileUrl: "/papers/by-course/database-systems-mid-2025.pdf", status: "approved" },
  { id: 11, courseId: 19, title: "Database Systems Final 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/database-systems-final-2025.pdf", status: "approved" },
  { id: 12, courseId: 20, title: "Operating Systems Final Spring 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/operating-systems-final-2025.pdf", status: "approved" },
  { id: 13, courseId: 24, title: "Pakistan Studies Final 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/pakistan-studies-final-2025.pdf", status: "approved" },
  { id: 14, courseId: 21, title: "Entrepreneurship Final 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/entrepreneurship-final-2025.pdf", status: "approved" },
  { id: 15, courseId: 22, title: "Professional Practices Final Spring 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/professional-practices-final-2025.pdf", status: "approved" },
  { id: 16, courseId: 25, title: "Computer Architecture Mid 2025", year: 2025, examType: "mid", teacherId: null, teacher: null, fileUrl: "/papers/by-course/computer-architecture-mid-2025.pdf", status: "approved" },
  { id: 17, courseId: 25, title: "Computer Architecture Final", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/computer-architecture-final.pdf", status: "approved" },
  { id: 18, courseId: 26, title: "Advance Database Systems Final 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/advance-database-systems-final-2025.pdf", status: "approved" },
  { id: 19, courseId: 30, title: "Technical and Business Writing Final", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/technical-business-writing-final.pdf", status: "approved" },
  { id: 20, courseId: 28, title: "Information Security Final 2025", year: 2025, examType: "final", teacherId: null, teacher: null, fileUrl: "/papers/by-course/information-security-final-2025.pdf", status: "approved" },
  { id: 21, courseId: 27, title: "Computer Graphics Mid 2025", year: 2025, examType: "mid", teacherId: null, teacher: null, fileUrl: "/papers/by-course/computer-graphics-mid-2025.pdf", status: "approved" },
];
