-- BSCS 2023-27 full scheme (46 courses). Prefer: npm run db:seed-courses
-- Papers: prefer npm run db:seed-real after courses exist

INSERT INTO courses (name, code, slug, semester, department) VALUES
  ('Programming Fundamentals', 'CS-101', 'programming-fundamentals', 1, 'Computer Science'),
  ('Digital Logic Design', 'CS-102', 'digital-logic-design', 1, 'Computer Science'),
  ('Application of ICT', 'GEDU-104', 'application-of-ict', 1, 'Computer Science'),
  ('Functional English', 'GEDU-101', 'functional-english', 1, 'Computer Science'),
  ('Islamic Studies', 'GEDU-102', 'islamic-studies', 1, 'Computer Science'),
  ('Object Oriented Programming', 'CS-151', 'object-oriented-programming', 2, 'Computer Science'),
  ('Computer Organization & Assembly Language', 'CS-152', 'computer-organization-assembly', 2, 'Computer Science'),
  ('Computer Networks', 'CS-153', 'computer-networks', 2, 'Computer Science'),
  ('Expository Writing', 'GEDU-151', 'expository-writing', 2, 'Computer Science'),
  ('Discrete Structures', 'GEDU-154', 'discrete-structures', 2, 'Computer Science'),
  ('Ideology and Constitution of Pakistan', 'GEDU-152', 'ideology-constitution-pakistan', 2, 'Computer Science'),
  ('Data Structures', 'CS-201', 'data-structures', 3, 'Computer Science'),
  ('Artificial Intelligence', 'CS-202', 'artificial-intelligence', 3, 'Computer Science'),
  ('Software Engineering', 'CS-203', 'software-engineering', 3, 'Computer Science'),
  ('Applied Physics', 'GEDU-205', 'applied-physics', 3, 'Computer Science'),
  ('Calculus and Analytic Geometry', 'GEDU-202', 'calculus', 3, 'Computer Science'),
  ('Introduction to Management', 'GEDU-237', 'intro-to-management', 3, 'Computer Science'),
  ('Analysis of Algorithms', 'CS-251', 'analysis-of-algorithms', 4, 'Computer Science'),
  ('Database Systems', 'CS-252', 'database-systems', 4, 'Computer Science'),
  ('Operating Systems', 'CS-253', 'operating-systems', 4, 'Computer Science'),
  ('Entrepreneurship', 'GEDU-251', 'entrepreneurship', 4, 'Computer Science'),
  ('Professional Practices', 'GEDU-267', 'professional-practices', 4, 'Computer Science'),
  ('Civics and Community Engagement', 'GEDU-252', 'civics-community-engagement', 4, 'Computer Science'),
  ('Pakistan Studies', 'HU-112', 'pakistan-studies', 4, 'Computer Science'),
  ('Computer Architecture', 'CS-301', 'computer-architecture', 5, 'Computer Science'),
  ('Advance Database Management Systems', 'CS-302', 'advance-database-systems', 5, 'Computer Science'),
  ('Computer Graphics', 'CS-321', 'computer-graphics', 5, 'Computer Science'),
  ('Information Security', 'CS-353', 'information-security', 5, 'Computer Science'),
  ('Multivariable Calculus', 'MATH-384', 'multivariable-calculus', 5, 'Computer Science'),
  ('Technical & Business Writing', 'ENG-384', 'technical-business-writing', 5, 'Computer Science'),
  ('Theory of Automata', 'CS-351', 'theory-of-automata', 6, 'Computer Science'),
  ('Object Oriented Analysis and Design', 'CS-303', 'ooad', 6, 'Computer Science'),
  ('Digital Image Processing', 'CS-452', 'digital-image-processing', 6, 'Computer Science'),
  ('Web Technologies', 'CS-355', 'web-technologies', 6, 'Computer Science'),
  ('Probability & Statistics', 'STAT-379', 'probability-statistics', 6, 'Computer Science'),
  ('Human Computer Interaction', 'CS-404', 'human-computer-interaction', 6, 'Computer Science'),
  ('Compiler Construction', 'CS-401', 'compiler-construction', 7, 'Computer Science'),
  ('Parallel and Distributed Computing', 'CS-451', 'parallel-distributed-computing', 7, 'Computer Science'),
  ('Mobile Application Development', 'CS-354', 'mobile-application-development', 7, 'Computer Science'),
  ('Linear Algebra', 'MATH-378', 'linear-algebra', 7, 'Computer Science'),
  ('Internship', 'CS-497', 'internship', 7, 'Computer Science'),
  ('Final Project (Part I)', 'CS-498', 'final-project-part-1', 7, 'Computer Science'),
  ('Software Testing & Quality Assurance', 'CS-402', 'software-testing-qa', 8, 'Computer Science'),
  ('Visual Programming', 'CS-352', 'visual-programming', 8, 'Computer Science'),
  ('Introduction to Marketing', 'MKT-373', 'introduction-to-marketing', 8, 'Computer Science'),
  ('Final Project (Part II)', 'CS-499', 'final-project-part-2', 8, 'Computer Science');
